####################################################
#
# Welcome to NewsFeed Jekyll Template
#
# Product Link : https://themeix.com/product/newsfeed-responsive-jekyll-news-magazine-theme/
# Version : v2.0.0
#
####################################################

# Site settings
title: "Newsfeed - Responsive News, Magazine Premium Jekyll Theme"
email: "themeix@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "NewsFeed is a responsive Jekyll template for your business website"
top_letest_news: true
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
facebook: https://facebook.com/themeix
instagram: https://instagram.com/themeix
twitter: https://twitter.com/themeix_com
pinterest: https://pinterest.com/themeix

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Post configuration
permalink: /:categories/:title/

autopages:
  enabled: true
  categories:
    layouts:
      - "category.html"
    title: ":cat"
    permalink: "/category/:cat"
  collections:
    layouts:
      - "category.html"
    title: " :coll" # :coll is replaced by the collection name
    permalink: "/:coll/"

  tags:
    layouts:
      - "tag.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

    
collections:
  projects:
    output: true
    permalink: /project/:path/
  services:
    output: true
    permalink: /service/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
